// ABOUT: Generates Google Play upload assets from raw device captures + brand tokens.
// ABOUT: Frames each capture on a branded 1080x1920 canvas; emits the feature graphic + app icon.
//
// Run with `pnpm store:assets`. Source captures live in ./captures (committed); generated,
// upload-ready PNGs are written to ./upload. Edit SHOTS below to change the set, order, or captions.
// See README.md for how to take fresh captures and the Play Console field each file maps to.

import sharp from 'sharp';
import { mkdirSync, copyFileSync } from 'node:fs';
import { resolve } from 'node:path';

const root = import.meta.dirname;
const capturesDir = resolve(root, 'captures');
const outDir = resolve(root, 'upload');
const repoRoot = resolve(root, '..');
mkdirSync(outDir, { recursive: true });

// Brand tokens — mirror src/styles.css and scripts/gen-icons.mjs.
const BG = '#F5F4F0';
const INK = '#0E1116';
const INK3 = '#4a5160';
const ACCENT = '#4EA47A';
const FONT = 'Figtree, Inter, Helvetica, Arial, sans-serif';

// The screenshot set: source capture → caption → output filename. Order is the upload order.
const SHOTS = [
  { src: 'home.png', caption: 'Set it up by voice — or tap.', out: '01-home.png' },
  { src: 'run.png', caption: 'Run it with a tap.', out: '02-run.png' },
  { src: 'stopwatch.png', caption: 'A count-up stopwatch, too.', out: '03-stopwatch.png' },
  { src: 'complete.png', caption: 'Save what works as a preset.', out: '04-complete.png' },
  { src: 'presets.png', caption: 'Your presets, on your device.', out: '05-presets.png' },
  { src: 'settings.png', caption: 'Yours to tune. No account, ever.', out: '06-settings.png' },
];

// Canvas + phone-frame geometry. PH derives from the OnePlus capture aspect (1440x3168); if you
// capture on a device with a different ratio, adjust SRC_W/SRC_H and PH follows.
const CW = 1080,
  CH = 1920;
const SRC_W = 1440,
  SRC_H = 3168;
const PW = 724;
const PH = Math.round(PW * (SRC_H / SRC_W));
const PX = Math.round((CW - PW) / 2);
const PY = 296;
const R = 52;

async function frame({ src, caption, out }) {
  const canvasSvg = `
<svg xmlns="http://www.w3.org/2000/svg" width="${CW}" height="${CH}">
  <defs>
    <linearGradient id="g" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#F3F2ED"/>
      <stop offset="1" stop-color="#E7E5DE"/>
    </linearGradient>
  </defs>
  <rect width="${CW}" height="${CH}" fill="url(#g)"/>
  <text x="${CW / 2}" y="176" text-anchor="middle" font-family="${FONT}" font-weight="600"
        font-size="58" fill="${INK}" letter-spacing="-0.02em">${caption}</text>
  <rect x="${CW / 2 - 32}" y="212" width="64" height="7" rx="3.5" fill="${ACCENT}"/>
</svg>`;

  const mask = Buffer.from(
    `<svg xmlns="http://www.w3.org/2000/svg" width="${PW}" height="${PH}"><rect width="${PW}" height="${PH}" rx="${R}" ry="${R}" fill="#fff"/></svg>`,
  );
  const phone = await sharp(resolve(capturesDir, src))
    .resize(PW, PH, { fit: 'fill' })
    .composite([{ input: mask, blend: 'dest-in' }])
    .png()
    .toBuffer();

  const pad = 60;
  const shadowShape = `<svg xmlns="http://www.w3.org/2000/svg" width="${PW + pad * 2}" height="${PH + pad * 2}"><rect x="${pad}" y="${pad}" width="${PW}" height="${PH}" rx="${R}" fill="${INK}" fill-opacity="0.22"/></svg>`;
  const shadow = await sharp(Buffer.from(shadowShape)).blur(34).png().toBuffer();

  await sharp(Buffer.from(canvasSvg))
    .composite([
      { input: shadow, left: PX - pad, top: PY - pad + 22 },
      { input: phone, left: PX, top: PY },
    ])
    .png()
    .toFile(resolve(outDir, out));
  console.log('wrote', out);
}

async function featureGraphic() {
  const svg = `
<svg xmlns="http://www.w3.org/2000/svg" width="1024" height="500">
  <rect width="1024" height="500" fill="${BG}"/>
  <text x="512" y="238" text-anchor="middle" font-family="${FONT}" font-weight="600"
        font-size="168" fill="${INK}" letter-spacing="-0.04em">takt</text>
  <rect x="482" y="292" width="60" height="8" rx="4" fill="${ACCENT}"/>
  <text x="512" y="372" text-anchor="middle" font-family="${FONT}" font-weight="500"
        font-size="46" fill="${INK3}">keep it going.</text>
</svg>`;
  await sharp(Buffer.from(svg)).png().toFile(resolve(outDir, 'feature-graphic-1024x500.png'));
  console.log('wrote feature-graphic-1024x500.png');
}

// App icon: the real 512x512 launcher icon (generated by scripts/gen-icons.mjs).
copyFileSync(resolve(repoRoot, 'public/icons/icon-512.png'), resolve(outDir, 'app-icon-512.png'));
console.log('wrote app-icon-512.png (copied from public/icons/icon-512.png)');

await featureGraphic();
for (const shot of SHOTS) await frame(shot);
console.log(`\nDone — ${SHOTS.length + 2} assets in ${outDir}`);
